version: "3.0"

services:
    backend:
        build: ./material-applications/example-backend/
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis
        container_name: backend
    
    frontend:
        build: ./material-applications/example-frontend/
        ports:
            - 5000:5000
        container_name: frontend
    
    redis:
        image: redis
        container_name: redis

