version: "3.5"

services:

     backend:
        build: ./material-applications/example-backend/
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis
            - POSTGRES_DATABASE=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=db
        container_name: backend

     frontend:
        build: ./material-applications/example-frontend/
        ports:
            - 5000:5000
        container_name: frontend

     redis:
        image: redis
        container_name: redis

     db:
        image: postgres:latest
        restart: always
        environment:
             -  POSTGRES_PASSWORD=postgres
             - POSTGRES_USER=postgres
