version: "3.5"

services:

     backend:
        build: ./material-applications/example-backend/
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis
            - POSTGRES_DATABASE=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=db
            - REQUEST_ORIGIN=http://localhost
        depends_on:
            - db
        container_name: backend

     frontend:
        build: ./material-applications/example-frontend/
        ports:
            - 5000:5000
        environment:
            - REACT_APP_BACKEND_URL=http://localhost/api/
        container_name: frontend

     redis:
        image: redis
        container_name: redis

     db:
        image: postgres:latest
        restart: always
        volumes:
             - ./database:/var/lib/postgresql/data
        environment:
             - POSTGRES_PASSWORD=postgres
             - POSTGRES_USER=postgres
        container_name: postgres

     nginx:
        image: nginx:1.24.0
        restart: unless-stopped
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        environment: 
            - NGINX_PORT=80
